import time

name = input("What's your name? ")
print("Hello " + name + ", here is how to cook pasta")
time.sleep(3)
print("Boil some water")
time.sleep(2)
print("Wait for 5 minutes")
time.sleep(2)
print("Add salt")
time.sleep(2)
print("Add the pasta")
time.sleep(2)
print("Cook for 10 minutes")
time.sleep(2)
print("Remove the water")
time.sleep(2)
print("Done!")